name: Assign Reviewer

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Choose random reviewers
        id: choose-reviewers
        run: |
          TEAM_MEMBERS="${{ env.TEAM_MEMBERS }}"
          TEAM_MEMBERS_ARRAY=(${TEAM_MEMBERS//, / })
          TEAM_MEMBERS_ARRAY=("${TEAM_MEMBERS_ARRAY[@]/${{ github.actor }}/}")
          SELECTED_REVIEWERS=($(shuf -e "${TEAM_MEMBERS_ARRAY[@]}" -n 2))
          SELECTED_REVIEWERS_STR=$(IFS=,; echo "${SELECTED_REVIEWERS[*]}")
          echo "SELECTED_REVIEWERS_STR=$SELECTED_REVIEWERS_STR" >> $GITHUB_ENV
          echo "Selected reviewers: $SELECTED_REVIEWERS_STR" # 지정된 리뷰어 로그

      - name: Assign reviewers
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: ${{ env.SELECTED_REVIEWERS_STR }}
          github-token: ${{ secrets.GH_TOKEN }}
